# setup_playbook.yml
---
- name: Device Setup
  hosts: "{{ target_ip }}"
  become: true

  tasks:
    - include_vars:
        file: ./setup-config/packages.yaml
    - include_tasks: ./setup-config/initial_setup.yaml
    - include_tasks: ./setup-config/tasks.yaml

#    - name: Reboot
#      command: sudo reboot
#      async: 0
#      poll: 0
#      become: false
#      ignore_errors: true
#
#    - name: Wait for the system to come back online
#      wait_for_connection:
#        timeout: 30  # Adjust the timeout as needed
      
#    - name: Continue with post-reboot tasks
#      debug:
#        msg: "Postreboot tasks completed successfully"  
