# setup_playbook.yml
---
- name: Raspberry Pi Setup
  hosts: 192.168.1.101
  become: true

  tasks:
    - include_vars:
        file: ./config/packages.yaml
    - include_tasks: ./config/initial_setup.yaml
    - include_tasks: ./config/tasks.yaml
     
    - name: Obtain eth0 ip address
      shell: "ip addr show eth0 | grep -oP '(?<=inet\\s)\\d+(\\.\\d+){3}'"
      register: eth0_ip_result

    - name: Display eth0 IP address
      debug:
        var: eth0_ip_result.stdout_lines

    - name: Reboot
      command: sudo reboot
      async: 0
      poll: 0
      become: false

   
