# setup_playbook.yml
---
- name: Raspberry Pi Setup
  hosts: 192.168.1.100
  become: true

  tasks:
    - include_vars:
        file: ./config/packages.yaml
    - include_tasks: ./config/initial_setup.yaml
    - include_tasks: ./config/tasks.yaml
